# Generated by Django 5.2.9 on 2026-01-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        (
            "organizations",
            "0005_alter_branch_options_alter_department_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.organization",
            ),
        ),
    ]
