# Generated by Django 6.0 on 2025-12-23 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "check_in_method",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("geo", "Geo Location"),
                            ("qr", "QR Code"),
                            ("biometric", "Biometric"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("absent", "Absent"),
                            ("week_off", "Week Off"),
                            ("holiday", "Holiday"),
                            ("on_leave", "On Leave"),
                            ("wfh", "Work From Home"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                (
                    "working_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("late_by_minutes", models.IntegerField(default=0)),
                ("early_by_minutes", models.IntegerField(default=0)),
                (
                    "check_in_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "check_in_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("is_regularized", models.BooleanField(default=False)),
                ("regularization_reason", models.TextField(blank=True)),
                (
                    "regularization_requested_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("regularization_status", models.CharField(blank=True, max_length=20)),
                (
                    "regularization_approved_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("regularization_remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
                (
                    "regularization_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("employee", "date")},
            },
        ),
    ]
