# Generated by Django 6.0 on 2025-12-24 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_qrtoken"),
        ("organizations", "0002_branch_geo_fence_radius_branch_latitude_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="qrtoken",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="qrtoken",
            name="branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.branch",
            ),
            preserve_default=False,
        ),
    ]
