# Generated by Django 5.2.9 on 2026-01-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_qrtoken_options_qrtoken_branch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={},
        ),
        migrations.AlterModelOptions(
            name="qrtoken",
            options={"verbose_name": "QR Token", "verbose_name_plural": "QR Tokens"},
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="early_by_minutes",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="is_regularized",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="late_by_minutes",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="regularization_approved_at",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="regularization_approved_by",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="regularization_reason",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="regularization_remarks",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="regularization_requested_at",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="regularization_status",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="remarks",
        ),
        migrations.RemoveField(
            model_name="attendance",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in_method",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("qr", "QR Scan"),
                    ("geo", "Geo-location"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("late", "Late"),
                    ("half_day", "Half Day"),
                    ("absent", "Absent"),
                    ("pending_approval", "Pending Approval"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="working_hours",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="qrtoken",
            name="token",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
