# Generated by Django 6.0 on 2025-12-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="geo_fence_radius",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="geo_fence_radius",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="organization",
            name="qr_refresh_interval",
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name="organization",
            name="require_approval_for_employees",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="require_geo_validation",
            field=models.BooleanField(default=True),
        ),
    ]
