# Generated by Django 5.2.9 on 2025-12-29 16:41

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_branch_geo_fence_radius_branch_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="address_line1",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="address_line2",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="city",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="country",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="email",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="financial_year_start",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="gst_number",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="pan_number",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="pincode",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="state",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="website",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="week_off_days",
        ),
        migrations.AddField(
            model_name="organization",
            name="schema_name",
            field=models.CharField(
                db_index=True,
                default="public",
                max_length=63,
                unique=True,
                validators=[django_tenants.postgresql_backend.base._check_schema_name],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
