# Generated by Django 5.2.9 on 2025-12-29 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_remove_organization_address_line1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="organizations.organization",
            ),
        ),
    ]
