# Generated by Django 5.2.9 on 2026-01-01 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_alter_branch_organization_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={},
        ),
        migrations.AlterModelOptions(
            name="shift",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="branch",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="OrgSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grace_period_mins", models.PositiveIntegerField(default=15)),
                ("geo_fence_radius_m", models.PositiveIntegerField(default=100)),
                ("allow_mock_location", models.BooleanField(default=False)),
                ("sandwich_rule_enabled", models.BooleanField(default=True)),
                ("regularization_window_days", models.PositiveIntegerField(default=7)),
                ("attendance_freeze_day", models.PositiveIntegerField(default=26)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
